* early-init.el
:PROPERTIES:
:HEADER-ARGS: :tangle early-init.el
:END:

emacs 刚启动时执行的配置文件,此时还未加载主配置文件

#+BEGIN_SRC emacs-lisp
  ;;; early-init.el --- Emacs pre-initialization config -*- lexical-binding: t -*-
  ;;; Commentary:

  ;;; Code:

  ;; 设置垃圾回收参数
  (setq gc-cons-threshold most-positive-fixnum)
  (setq gc-cons-percentage 0.6)

  ;; 禁止启动的首页展示
  (setq package-enable-at-startup nil)

  ;; 禁止自动缩放窗口先
  (setq frame-inhibit-implied-resize t)

  ;; 禁止菜单栏、工具栏、滚动条模式，禁止启动屏幕和文件对话框
  (menu-bar-mode -1)
  (tool-bar-mode -1)
  (scroll-bar-mode -1)
  (setq inhibit-splash-screen t)
  (setq use-file-dialog nil)

  ;; 此阶段不编译
  (setq comp-deferred-compilation nil)

  ; 不显示编译警告
  (setq native-comp-async-report-warnings-errors nil)

  ; 设置字体
  (set-face-attribute 'default nil :height 140)

  ; custom.el
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (when (file-exists-p custom-file)
    (load custom-file))

  (provide 'early-init)
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;;; early-init.el ends here
#+END_SRC

* init.el
:PROPERTIES:
:HEADER-ARGS: :tangle init.el
:END:

~init.el~ 是 emacs 的主配置文件

** init.el 文件头

#+BEGIN_SRC emacs-lisp
;;; init.el --- The main init entry for Emacs -*- lexical-binding: t -*-
;;; Commentary:

;;; Code:

#+END_SRC

** 使用 ~elpaca~ 作为包管理器

[[https://github.com/progfolio/elpaca][elpaca 是一款更加现代化的 GUI Emacs 包管理器，它拥有着相较于 straight.el]]

以下源自官方的安装指南：

#+BEGIN_SRC emacs-lisp
  (defvar elpaca-installer-version 0.7)
  (defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
  (defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
  (defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
  (defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
				:ref nil :depth 1
				:files (:defaults "elpaca-test.el" (:exclude "extensions"))
				:build (:not elpaca--activate-package)))
  (let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
	 (build (expand-file-name "elpaca/" elpaca-builds-directory))
	 (order (cdr elpaca-order))
	 (default-directory repo))
    (add-to-list 'load-path (if (file-exists-p build) build repo))
    (unless (file-exists-p repo)
      (make-directory repo t)
      (when (< emacs-major-version 28) (require 'subr-x))
      (condition-case-unless-debug err
	  (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
		   ((zerop (apply #'call-process `("git" nil ,buffer t "clone"
						   ,@(when-let ((depth (plist-get order :depth)))
						       (list (format "--depth=%d" depth) "--no-single-branch"))
						   ,(plist-get order :repo) ,repo))))
		   ((zerop (call-process "git" nil buffer t "checkout"
					 (or (plist-get order :ref) "--"))))
		   (emacs (concat invocation-directory invocation-name))
		   ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
					 "--eval" "(byte-recompile-directory \".\" 0 'force)")))
		   ((require 'elpaca))
		   ((elpaca-generate-autoloads "elpaca" repo)))
	      (progn (message "%s" (buffer-string)) (kill-buffer buffer))
	    (error "%s" (with-current-buffer buffer (buffer-string))))
	((error) (warn "%s" err) (delete-directory repo 'recursive))))
    (unless (require 'elpaca-autoloads nil t)
      (require 'elpaca)
      (elpaca-generate-autoloads "elpaca" repo)
      (load "./elpaca-autoloads")))
  (add-hook 'after-init-hook #'elpaca-process-queues)
  (elpaca `(,@elpaca-order))
#+END_SRC

** 为 ~elpaca~ 安装 ~use-package~

设置 ~use-package~ 自动安装包，然后启用 ~elpaca-use-package-mode~

#+BEGIN_SRC emacs-lisp
  (setq use-package-always-ensure t)

  (elpaca elpaca-use-package
  ;; Enable use-package :ensure support for Elpaca.
  (elpaca-use-package-mode))
#+END_SRC

** 加载其他的模块

#+BEGIN_SRC emacs-lisp

  ;; 将lisp目录放到加载路径的前面以加快启动速度
  (let ((dir (locate-user-emacs-file "lisp")))
    (add-to-list 'load-path (file-name-as-directory dir)))

  ;; 加载各模块化配置
  ;; 不要在`*message*'缓冲区显示加载模块化配置的信息
  (with-temp-message ""
    (require 'init-ui)                    ; UI交互
    (require 'init-edit)                  ; 编辑行为
    (require 'init-org)                   ; org相关设置
    (require 'init-completion)            ; 补全系统
    (require 'init-dev)                   ; 版本管理
    (require 'init-tools)                 ; tools
    (require 'init-lsp)                   ; lsp 支持
    (require 'init-treesitter)            ; treesitter 支持
    (require 'init-book)                  ; book 支持
    (require 'init-lang)                  ; lang 支持
    )

#+END_SRC

** init.el 文件尾

#+BEGIN_SRC emacs-lisp

(provide 'init)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init.el ends here
#+END_SRC

* init-ui.el
:PROPERTIES:
:HEADER-ARGS: :tangle lisp/init-ui.el :mkdirp yes
:END:

** init-ui.el 文件头
#+BEGIN_SRC emacs-lisp
;;; init-ui.el --- UI settings -*- lexical-binding: t -*-
;;; Commentary:

;;; Code:

#+END_SRC

** ef主题

[[https://protesilaos.com/emacs/ef-themes][ef themes]] 是我非常喜欢的一个主题包。

#+BEGIN_SRC emacs-lisp
(use-package ef-themes
  :init
  (ef-themes-select 'ef-cyprus))
#+END_SRC

** 调整启动窗口大小

#+BEGIN_SRC emacs-lisp
;; 设置窗口大小，仅仅在图形界面需要设置
(when (display-graphic-p)
  (let ((top    0)                                     ; 顶不留空
        (left   (/ (x-display-pixel-width) 10))        ; 左边空10%
        (height (round (* 0.8                          ; 窗体高度为0.8倍的显示高度
                          (/ (x-display-pixel-height)
                             (frame-char-height))))))
    (let ((width  (round (* 2.5 height))))             ; 窗体宽度为2.5倍高度
      (setq default-frame-alist nil)
      (add-to-list 'default-frame-alist (cons 'top top))
      (add-to-list 'default-frame-alist (cons 'left left))
      (add-to-list 'default-frame-alist (cons 'height height))
      (add-to-list 'default-frame-alist (cons 'width width)))))
#+END_SRC

** 其他UI零散设置项

#+begin_src emacs-lisp
;; 禁用一些GUI特性
(setq use-dialog-box nil)               ; 鼠标操作不使用对话框
(setq inhibit-default-init t)           ; 不加载 `default' 库
(setq inhibit-startup-screen t)         ; 不加载启动画面
(setq inhibit-startup-message t)        ; 不加载启动消息
(setq inhibit-startup-buffer-menu t)    ; 不显示缓冲区列表

;; 草稿缓冲区默认文字设置
(setq initial-scratch-message (concat ";; Happy hacking, "
                                      (capitalize user-login-name) " - Emacs ♥ you!\n\n"))

;; 设置缓冲区的文字方向为从左到右
(setq bidi-paragraph-direction 'left-to-right)
;; 禁止使用双向括号算法
;; (setq bidi-inhibit-bpa t)

;; 设置自动折行宽度为80个字符，默认值为70
(setq-default fill-column 80)

;; 设置大文件阈值为100MB，默认10MB
(setq large-file-warning-threshold 100000000)

;; 以16进制显示字节数
(setq display-raw-bytes-as-hex t)
;; 有输入时禁止 `fontification' 相关的函数钩子，能让滚动更顺滑
(setq redisplay-skip-fontification-on-input t)

;; 禁止响铃
(setq ring-bell-function 'ignore)

;; 禁止闪烁光标
(blink-cursor-mode -1)

;; 在光标处而非鼠标所在位置粘贴
(setq mouse-yank-at-point t)

;; 拷贝粘贴设置
(setq select-enable-primary nil)        ; 选择文字时不拷贝
(setq select-enable-clipboard t)        ; 拷贝时使用剪贴板

;; 鼠标滚动设置
(setq scroll-step 2)
(setq scroll-margin 2)
(setq hscroll-step 2)
(setq hscroll-margin 2)
(setq scroll-conservatively 101)
(setq scroll-up-aggressively 0.01)
(setq scroll-down-aggressively 0.01)
(setq scroll-preserve-screen-position 'always)

;; 对于高的行禁止自动垂直滚动
(setq auto-window-vscroll nil)

;; 设置新分屏打开的位置的阈值
(setq split-width-threshold (assoc-default 'width default-frame-alist))
(setq split-height-threshold nil)

;; TAB键设置，在Emacs里不使用TAB键，所有的TAB默认为4个空格
(setq-default indent-tabs-mode nil)
(setq-default tab-width 4)

;; yes或no提示设置，通过下面这个函数设置当缓冲区名字匹配到预设的字符串时自动回答yes
(setq original-y-or-n-p 'y-or-n-p)
(defalias 'original-y-or-n-p (symbol-function 'y-or-n-p))
(defun default-yes-sometimes (prompt)
  "automatically say y when buffer name match following string"
  (if (or
	   (string-match "has a running process" prompt)
	   (string-match "does not exist; create" prompt)
	   (string-match "modified; kill anyway" prompt)
	   (string-match "Delete buffer using" prompt)
	   (string-match "Kill buffer of" prompt)
	   (string-match "still connected.  Kill it?" prompt)
	   (string-match "Shutdown the client's kernel" prompt)
	   (string-match "kill them and exit anyway" prompt)
	   (string-match "Revert buffer from file" prompt)
	   (string-match "Kill Dired buffer of" prompt)
	   (string-match "delete buffer using" prompt)
       (string-match "Kill all pass entry" prompt)
       (string-match "for all cursors" prompt)
	   (string-match "Do you want edit the entry" prompt))
	  t
    (original-y-or-n-p prompt)))
(defalias 'yes-or-no-p 'default-yes-sometimes)
(defalias 'y-or-n-p 'default-yes-sometimes)

;; 设置剪贴板历史长度300，默认为60
(setq kill-ring-max 200)

;; 在剪贴板里不存储重复内容
(setq kill-do-not-save-duplicates t)

;; 设置位置记录长度为6，默认为16
;; 可以使用 `counsel-mark-ring' or `consult-mark' (C-x j) 来访问光标位置记录
;; 使用 C-x C-SPC 执行 `pop-global-mark' 直接跳转到上一个全局位置处
;; 使用 C-u C-SPC 跳转到本地位置处
(setq mark-ring-max 6)
(setq global-mark-ring-max 6)

;; 设置 emacs-lisp 的限制
(setq max-lisp-eval-depth 10000)        ; 默认值为 800
(setq max-specpdl-size 10000)           ; 默认值为 1600

;; 启用 `list-timers', `list-threads' 这两个命令
(put 'list-timers 'disabled nil)
(put 'list-threads 'disabled nil)

;; 在命令行里支持鼠标
(xterm-mouse-mode 1)

;; 在模式栏上显示当前光标的列号
(column-number-mode t)
#+end_src

** 编码设置

统一使用 UTF-8 编码。

#+begin_src emacs-lisp
;; 配置所有的编码为UTF-8，参考：
;; https://thraxys.wordpress.com/2016/01/13/utf-8-in-emacs-everywhere-forever/
(setq locale-coding-system 'utf-8)
(set-terminal-coding-system 'utf-8)
(set-keyboard-coding-system 'utf-8)
(set-selection-coding-system 'utf-8)
(set-default-coding-systems 'utf-8)
(set-language-environment 'utf-8)
(set-clipboard-coding-system 'utf-8)
(set-file-name-coding-system 'utf-8)
(set-buffer-file-coding-system 'utf-8)
(prefer-coding-system 'utf-8)
(modify-coding-system-alist 'process "*" 'utf-8)
(when (display-graphic-p)
  (setq x-select-request-type '(UTF8_STRING COMPOUND_TEXT TEXT STRING)))
#+end_src

** 模式栏设置
*** doom-modeline插件

[[https://github.com/seagle0128/doom-modeline][doom-modeline]] 是一个模式栏美化插件。

#+begin_src emacs-lisp
(use-package doom-modeline
  :config (doom-modeline-mode)
  :custom
  (doom-modeline-irc nil)
  (doom-modeline-mu4e nil)
  (doom-modeline-gnus nil)
  (doom-modeline-github nil)
  (doom-modeline-buffer-file-name-style 'truncate-upto-root) ; : auto
  (doom-modeline-persp-name nil)
  (doom-modeline-unicode-fallback t)
  (doom-modeline-enable-word-count nil))
#+end_src

*** minions插件
[[https://github.com/tarsius/minions][minions]] 插件能让模式栏变得清爽，将次要模式隐藏起来。

#+BEGIN_SRC emacs-lisp
(use-package minions
  :config (minions-mode))
#+END_SRC

** init-ui.el 文件尾

#+BEGIN_SRC emacs-lisp

(provide 'init-ui)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init-ui.el ends here
#+END_SRC

* init-edit.el
:PROPERTIES:
:HEADER-ARGS: :tangle lisp/init-edit.el :mkdirp yes
:END:

** init-edit.el 文件头

#+BEGIN_SRC emacs-lisp
;;; init-edit.el --- Editing settings -*- lexical-binding: t -*-
;;; Commentary:

;;; Code:

#+END_SRC

** Emacs备份设置

不使用Emacs的自动备份设置。

#+BEGIN_SRC emacs-lisp
(setq make-backup-files nil)                                  ; 不自动备份
(setq auto-save-default nil)                                  ; 不使用Emacs自带的自动保存
#+END_SRC

** 解除一些不常用的快捷键

将一些不常用的快捷键解除，防止误操作。

#+BEGIN_SRC emacs-lisp
;; 解除不常用的快捷键定义
(global-set-key (kbd "C-z") nil)
(global-set-key (kbd "s-q") nil)
(global-set-key (kbd "M-z") nil)
(global-set-key (kbd "M-m") nil)
(global-set-key (kbd "C-x C-z") nil)
(global-set-key [mouse-2] nil)
#+END_SRC

** 自动重载设置

当我们的文件发生了改变后，我们希望Emacs里打开的永远是最新的文件，这个时候，我们需要对自动重载进行设置，让我们的Emacs在文件发生改变的时候自动重载文件。

#+BEGIN_SRC emacs-lisp
(use-package autorevert
  :ensure nil
  :config (global-auto-revert-mode)
  :custom
  (auto-revert-interval 10)
  (auto-revert-avoid-polling t)
  (auto-revert-verbose nil)
  (auto-revert-remote-files t)
  (auto-revert-check-vc-info t)
  (global-auto-revert-non-file-buffers t))
#+END_SRC

** 🌈彩虹括号匹配

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] 插件将多彩显示括号等分隔符。

#+begin_src emacs-lisp
  (use-package rainbow-delimiters
    :ensure t
    :hook (prog-mode . rainbow-delimiters-mode))
#+end_src

** savehist 保存 ~minibuffer~ 历史记录

#+BEGIN_SRC emacs-lisp
  (use-package savehist
    :ensure nil
    :init
    (savehist-mode))
#+END_SRC

** ~save-place~ 记住关闭文件是光标位置
#+begin_src emacs-lisp
  ;; 自动记住每个文件的最后一次访问的光标位置
  (use-package saveplace
    :ensure nil
    :init (save-place-mode))
#+end_src

** ~recentf~ 记住最近打开文件的历史记录

#+begin_src emacs-lisp
  (use-package recentf
    :ensure nil
    :init (recentf-mode)
    :custom
    (recentf-max-saved-items 300))
#+end_src

** ~undo-tree~ 增强 ~undo~

#+begin_src emacs-lisp
  (use-package undo-tree
    :init (global-undo-tree-mode)
    :config
    ;; don't save undo history to local files
    (setq undo-tree-auto-save-history nil)
    )
#+end_src

** ~curx~

~curx~ 提供了一系列的增强，如移动增强、删除增强等优化功能。

#+begin_src emacs-lisp
  (use-package crux
    :bind (("C-a" . crux-move-beginning-of-line)
           ("C-x 4 t" . crux-transpose-windows)
           ("C-x K" . crux-kill-other-buffers)
           ("C-k" . crux-smart-kill-line)
           ("C-c r" . crux-rename-file-and-buffer)
           ("C-x DEL" . crux-kill-line-backwards))
    :config
    (crux-with-region-or-buffer indent-region)
    (crux-with-region-or-buffer untabify)
    (crux-with-region-or-point-to-eol kill-ring-save)
    (defalias 'rename-file-and-buffer #'crux-rename-file-and-buffer))
#+end_src

** init-edit.el 文件尾

#+BEGIN_SRC emacs-lisp
;; (message "init-base configuration: %.2fs"
;;          (float-time (time-subtract (current-time) my/init-base-start-time)))

(provide 'init-edit)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init-edit.el ends here
#+END_SRC

* init-org.el
:PROPERTIES:
:HEADER-ARGS: :tangle lisp/init-org.el :mkdirp yes
:END:

** init-org.el 文件头

#+BEGIN_SRC emacs-lisp
;;; init-org.el --- Org mode settings -*- lexical-binding: t -*-
;;; Commentary:

;;; Code:

#+END_SRC

** org 配置

#+begin_src emacs-lisp
  (use-package org
    :ensure nil
    :mode ("\\.org\\'" . org-mode)
    :hook ((org-mode . visual-line-mode)
         (org-mode . my/org-prettify-symbols))
    :commands (org-find-exact-headline-in-buffer org-set-tags)
    :custom-face
    ;; 设置Org mode标题以及每级标题行的大小
    (org-document-title ((t (:height 1.75 :weight bold))))
    (org-level-1 ((t (:height 1.2 :weight bold))))
    (org-level-2 ((t (:height 1.15 :weight bold))))
    (org-level-3 ((t (:height 1.1 :weight bold))))
    (org-level-4 ((t (:height 1.05 :weight bold))))
    (org-level-5 ((t (:height 1.0 :weight bold))))
    (org-level-6 ((t (:height 1.0 :weight bold))))
    (org-level-7 ((t (:height 1.0 :weight bold))))
    (org-level-8 ((t (:height 1.0 :weight bold))))
    (org-level-9 ((t (:height 1.0 :weight bold))))
    ;; 设置代码块用上下边线包裹
    (org-block-begin-line ((t (:underline t :background unspecified))))
    (org-block-end-line ((t (:overline t :underline nil :background unspecified))))
    :config
    ;; ================================
    ;; 在org mode里美化字符串
    ;; ================================
    (defun my/org-prettify-symbols ()
      (setq prettify-symbols-alist
          (mapcan (lambda (x) (list x (cons (upcase (car x)) (cdr x))))
                  '(
                    ("[ ]"              . 9744)         ; ☐
                    ("[X]"              . 9745)         ; ☑
                    ("[-]"              . 8863)         ; ⊟
                    ("#+begin_src"      . 9998)         ; ✎
                    ("#+end_src"        . 9998)         ; ✎
                    ("#+begin_example"  . 129083)       ; 🠻
                    ("#+end_example"    . 129081)       ; 🠹
                    ("#+results:"       . 9776)         ; ☰
                    ("#+attr_latex:"    . "🄛")
                    ("#+attr_html:"     . "🄗")
                    ("#+attr_org:"      . "🄞")
                    ("#+name:"          . "🄝")         ; 127261
                    ("#+caption:"       . "🄒")         ; 127250
                    ("#+date:"          . "📅")         ; 128197
                    ("#+author:"        . "💁")         ; 128100
                    ("#+setupfile:"     . 128221)       ; 📝
                    ("#+email:"         . 128231)       ; 📧
                    ("#+startup:"       . 10034)        ; ✲
                    ("#+options:"       . 9965)         ; ⛭
                    ("#+title:"         . 10162)        ; ➲
                    ("#+subtitle:"      . 11146)        ; ⮊
                    ("#+downloaded:"    . 8650)         ; ⇊
                    ("#+language:"      . 128441)       ; 🖹
                    ("#+begin_quote"    . 187)          ; »
                    ("#+end_quote"      . 171)          ; «
                    ("#+begin_results"  . 8943)         ; ⋯
                    ("#+end_results"    . 8943)         ; ⋯
                    )))
      (setq prettify-symbols-unprettify-at-point t)
      (prettify-symbols-mode 1))

    ;; 提升latex预览的图片清晰度
    (plist-put org-format-latex-options :scale 1.8)

    ;; 设置标题行之间总是有空格；列表之间根据情况自动加空格
    (setq org-blank-before-new-entry '((heading . t)
                                     (plain-list-item . auto)
                                     ))
    :custom
    ;; 启用一些子模块
    (org-modules '(ol-bibtex ol-gnus ol-info ol-eww org-habit org-protocol))
    ;; 在按M-RET时，是否根据光标所在的位置分行，这里设置为是
    ;; (org-M-RET-may-split-line '((default . nil)))
    ;; 一些Org mode自带的美化设置
    ;; 标题行美化
    (org-fontify-whole-heading-line t)
    ;; 设置标题行折叠符号
    (org-ellipsis " ▾")
    ;; 在活动区域内的所有标题栏执行某些命令
    (org-loop-over-headlines-in-active-region t)
    ;; TODO标签美化
    (org-fontify-todo-headline t)
    ;; DONE标签美化
    (org-fontify-done-headline t)
    ;; 引用块美化
    (org-fontify-quote-and-verse-blocks t)
    ;; 隐藏宏标记
    (org-hide-macro-markers t)
    ;; 隐藏强调标签
    (org-hide-emphasis-markers t)
    ;; 高亮latex语法
    (org-highlight-latex-and-related '(native script entities))
    ;; 以UTF-8显示
    (org-pretty-entities t)
    ;; 是否隐藏标题栏的前置星号，这里我们通过org-modern来隐藏
    ;; (org-hide-leading-stars t)
    ;; 当启用缩进模式时自动隐藏前置星号
    (org-indent-mode-turns-on-hiding-stars t)
    ;; 自动启用缩进
    (org-startup-indented nil)
    ;; 根据标题栏自动缩进文本
    (org-adapt-indentation nil)
    ;; 自动显示图片
    (org-startup-with-inline-images t)
    ;; 默认以Overview的模式展示标题行
    (org-startup-folded 'overview)
    ;; 允许字母列表
    (org-list-allow-alphabetical t)
    ;; 列表的下一级设置
    (org-list-demote-modify-bullet '(
								   ("-"  . "+")
                                   ("+"  . "1.")
								   ("1." . "a.")
								   ))
    ;; 编辑时检查是否在折叠的不可见区域
    (org-fold-catch-invisible-edits 'smart)
    ;; 在当前位置插入新标题行还是在当前标题行后插入，这里设置为当前位置
    (org-insert-heading-respect-content nil)
    ;; 设置图片的最大宽度，如果有imagemagick支持将会改变图片实际宽度
    ;; 四种设置方法：(1080), 1080, t, nil
    (org-image-actual-width nil)
    ;; imenu的最大深度，默认为2
    (org-imenu-depth 4)
    ;; 回车要不要触发链接，这里设置不触发
    (org-return-follows-link nil)
    ;; 上标^下标_是否需要特殊字符包裹，这里设置需要用大括号包裹
    (org-use-sub-superscripts '{})
    ;; 复制粘贴标题行的时候删除id
    (org-clone-delete-id t)
    ;; 粘贴时调整标题行的级别
    (org-yank-adjusted-subtrees t)

    ;; TOOD的关键词设置，可以设置不同的组
    (org-todo-keywords '((sequence "TODO(t)" "HOLD(h!)" "WIP(i!)" "WAIT(w!)" "|" "DONE(d!)" "CANCELLED(c@/!)")
					   (sequence "REPORT(r)" "BUG(b)" "KNOWNCAUSE(k)" "|" "FIXED(f!)")))
    ;; TODO关键词的样式设置
    (org-todo-keyword-faces '(("TODO"       :foreground "#7c7c75" :weight bold)
							("HOLD"       :foreground "#feb24c" :weight bold)
							("WIP"        :foreground "#0098dd" :weight bold)
							("WAIT"       :foreground "#9f7efe" :weight bold)
							("DONE"       :foreground "#50a14f" :weight bold)
							("CANCELLED"  :foreground "#ff6480" :weight bold)
							("REPORT"     :foreground "magenta" :weight bold)
							("BUG"        :foreground "red"     :weight bold)
							("KNOWNCAUSE" :foreground "yellow"  :weight bold)
							("FIXED"      :foreground "green"   :weight bold)))
    ;; 当标题行状态变化时标签同步发生的变化
    ;; Moving a task to CANCELLED adds a CANCELLED tag
    ;; Moving a task to WAIT adds a WAIT tag
    ;; Moving a task to HOLD adds WAIT and HOLD tags
    ;; Moving a task to a done state removes WAIT and HOLD tags
    ;; Moving a task to TODO removes WAIT, CANCELLED, and HOLD tags
    ;; Moving a task to DONE removes WAIT, CANCELLED, and HOLD tags
    (org-todo-state-tags-triggers
     (quote (("CANCELLED" ("CANCELLED" . t))
		   ("WAIT" ("WAIT" . t))
		   ("HOLD" ("WAIT") ("HOLD" . t))
		   (done ("WAIT") ("HOLD"))
		   ("TODO" ("WAIT") ("CANCELLED") ("HOLD"))
		   ("DONE" ("WAIT") ("CANCELLED") ("HOLD")))))
    ;; 使用专家模式选择标题栏状态
    (org-use-fast-todo-selection 'expert)
    ;; 父子标题栏状态有依赖
    (org-enforce-todo-dependencies t)
    ;; 标题栏和任务复选框有依赖
    (org-enforce-todo-checkbox-dependencies t)
    ;; 优先级样式设置
    (org-priority-faces '((?A :foreground "red")
						(?B :foreground "orange")
						(?C :foreground "yellow")))
    ;; 标题行全局属性设置
    (org-global-properties '(("EFFORT_ALL" . "0:15 0:30 0:45 1:00 2:00 3:00 4:00 5:00 6:00 7:00 8:00")
						   ("APPT_WARNTIME_ALL" . "0 5 10 15 20 25 30 45 60")
						   ("RISK_ALL" . "Low Medium High")
						   ("STYLE_ALL" . "habit")))
    ;; Org columns的默认格式
    (org-columns-default-format "%25ITEM %TODO %SCHEDULED %DEADLINE %3PRIORITY %TAGS %CLOCKSUM %EFFORT{:}")
    ;; 当状态从DONE改成其他状态时，移除 CLOSED: [timestamp]
    (org-closed-keep-when-no-todo t)
    ;; DONE时加上时间戳
    (org-log-done 'time)
    ;; 重复执行时加上时间戳
    (org-log-repeat 'time)
    ;; Deadline修改时加上一条记录
    (org-log-redeadline 'note)
    ;; Schedule修改时加上一条记录
    (org-log-reschedule 'note)
    ;; 以抽屉的方式记录
    (org-log-into-drawer t)
    ;; 紧接着标题行或者计划/截止时间戳后加上记录抽屉
    (org-log-state-notes-insert-after-drawers nil)

    ;; refile使用缓存
    (org-refile-use-cache t)
    ;; refile的目的地，这里设置的是agenda文件的所有标题
    (org-refile-targets '((org-agenda-files . (:maxlevel . 9))))
    ;; 将文件名加入到路径
    (org-refile-use-outline-path 'file)
    ;; 是否按步骤refile
    (org-outline-path-complete-in-steps nil)
    ;; 允许创建新的标题行，但需要确认
    (org-refile-allow-creating-parent-nodes 'confirm)

    ;; 设置标签的默认位置，默认是第77列右对齐
    ;; (org-tags-column -77)
    ;; 自动对齐标签
    (org-auto-align-tags t)
    ;; 标签不继承
    (org-use-tag-inheritance nil)
    ;; 在日程视图的标签不继承
    (org-agenda-use-tag-inheritance nil)
    ;; 标签快速选择
    (org-use-fast-tag-selection t)
    ;; 标签选择不需要回车确认
    (org-fast-tag-selection-single-key t)
    ;; 定义了有序属性的标题行也加上 OREDERD 标签
    (org-track-ordered-property-with-tag t)
    ;; 始终存在的的标签
    (org-tag-persistent-alist '(("read"     . ?r)
							  ("mail"     . ?m)
							  ("emacs"    . ?e)
							  ("study"    . ?s)
							  ("work"     . ?w)))
    ;; 预定义好的标签
    (org-tag-alist '((:startgroup)
				   ("crypt"    . ?c)
				   ("linux"    . ?l)
				   ("apple"    . ?a)
				   ("noexport" . ?n)
				   ("ignore"   . ?i)
				   ("TOC"      . ?t)
				   (:endgroup)))
  )
#+end_src

** org-modern 美化 org

#+begin_src emacs-lisp
  (use-package org-modern
    :ensure t
    :hook (after-init . (lambda ()
                          (setq org-modern-hide-stars 'leading)
                          (global-org-modern-mode t)))
    :config
    ;; 标题行型号字符
    (setq org-modern-star ["◉" "○" "✸" "✳" "◈" "◇" "✿" "❀" "✜"])
    ;; 额外的行间距，0.1表示10%，1表示1px
    (setq-default line-spacing 0.1)
    ;; tag边框宽度，还可以设置为 `auto' 即自动计算
    (setq org-modern-label-border 1)
    ;; 设置表格竖线宽度，默认为3
    (setq org-modern-table-vertical 2)
    ;; 设置表格横线为0，默认为0.1
    (setq org-modern-table-horizontal 0)
    ;; 复选框美化
    (setq org-modern-checkbox
          '((?X . #("▢✓" 0 2 (composition ((2)))))
            (?- . #("▢–" 0 2 (composition ((2)))))
            (?\s . #("▢" 0 1 (composition ((1)))))))
    ;; 列表符号美化
    (setq org-modern-list
          '((?- . "•")
            (?+ . "◦")
            (?* . "▹")))
    ;; 代码块左边加上一条竖边线（需要Org mode顶头，如果启用了 `visual-fill-column-mode' 会很难看）
    (setq org-modern-block-fringe t)
    ;; 代码块类型美化，我们使用了 `prettify-symbols-mode'
    (setq org-modern-block-name nil)
    ;; #+关键字美化，我们使用了 `prettify-symbols-mode'
    (setq org-modern-keyword nil)
    )
#+end_src

** org-appear 自动展开强调链接

当我们的光标移动到Org mode里的强调、链接上时，会自动展开，这样方便进行编辑。

#+begin_src emacs-lisp
  (use-package
   org-appear
   :ensure t
   :hook (org-mode . org-appear-mode)
   :config
   (setq org-appear-autolinks t)
   (setq org-appear-autosubmarkers t)
   (setq org-appear-autoentities t)
   (setq org-appear-autokeywords t)
   (setq org-appear-inside-latex t))
#+end_src

** org-auto-tangle 自动 tangle 设置

[[https://github.com/yilkalargaw/org-auto-tangle][org-auto-tangle]] 插件可以在Org mode下自动进行tangle。

#+BEGIN_SRC emacs-lisp
  (use-package
   org-auto-tangle
   :ensure t
   :hook (org-mode . org-auto-tangle-mode)
   :config (setq org-auto-tangle-default t))
#+END_SRC

** toc-org

为 org 生成目录。

#+begin_src emacs-lisp
  (use-package toc-org
    :hook (org-mode . toc-org-mode))
#+end_src

** 插入链接

我们可以在 org 文件里通过 ~C-c C-l~ 来插入链接。

#+begin_src emacs-lisp
  (use-package
   ol
   :ensure nil
   :defer t
   :custom (org-link-keep-stored-after-insertion t)
   (org-link-abbrev-alist
    '(("github" . "https://github.com/")
      ("gitlab" . "https://gitlab.com/")
      ("google" . "https://google.com/search?q=")
      ("baidu" . "https://baidu.com/s?wd=")
      ("rfc" . "https://tools.ietf.org/html/")
      ("wiki" . "https://en.wikipedia.org/wiki/")
      ("youtube" . "https://youtube.com/watch?v=")
      ("zhihu" . "https://zhihu.com/question/"))))
#+end_src

** org-download 粘贴图片

使用 org-download 从剪切板粘贴图片或者直接拖入文件

#+begin_src emacs-lisp
  (use-package
   org-download
   :init (setq org-download-annotate-function (lambda (_link) ""))
   :hook (dired-mode . org-download-enable))
#+end_src

** init-org.el 文件尾

#+BEGIN_SRC emacs-lisp

  (provide 'init-org)
  ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;;; init-org.el ends here
#+END_SRC

* init-completion.el
:PROPERTIES:
:HEADER-ARGS: :tangle lisp/init-completion.el :mkdirp yes
:END:

Emacs的补全设置。

** init-completion.el 文件头
#+BEGIN_SRC emacs-lisp
;;; init-completion.el --- Completion settings -*- lexical-binding: t -*-
;;; Commentary:

;;; Code:

#+END_SRC

** 括号自动补全支持

使用 emacs 内置的包来实现括号补全

#+BEGIN_SRC emacs-lisp
  (use-package
   elec-pair
   :ensure nil
   :hook (after-init . electric-pair-mode)
   :init
   (setq electric-pair-inhibit-predicate 'electric-pair-conservative-inhibit))
#+END_SRC
** vertico 垂直补全系统

[[https://github.com/minad/vertico][vertico]] 插件提供了一个垂直样式的补全系统。

#+BEGIN_SRC emacs-lisp
  (use-package
   vertico
   :custom
   (vertico-scroll-margin 0) ;; Different scroll margin
   ;(vertico-count 20) ;; Show more candidates
   (vertico-resize t) ;; Grow and shrink the Vertico minibuffer
   (vertico-cycle t) ;; Enable cycling for `vertico-next/previous'
   :init (vertico-mode))
#+END_SRC

一些关于 emacs 的配置，可以提升 ~vertico~ 体验：

#+BEGIN_SRC emacs-lisp
  (use-package
   emacs
   :ensure nil
   :custom
   ;; Support opening new minibuffers from inside existing minibuffers.
   (enable-recursive-minibuffers t)
   ;; Emacs 28 and newer: Hide commands in M-x which do not work in the current
   ;; mode.  Vertico commands are hidden in normal buffers. This setting is
   ;; useful beyond Vertico.
   (read-extended-command-predicate #'command-completion-default-include-p)
   :init
   ;; Add prompt indicator to `completing-read-multiple'.
   ;; We display [CRM<separator>], e.g., [CRM,] if the separator is a comma.
   (defun crm-indicator (args)
     (cons
      (format "[CRM%s] %s"
              (replace-regexp-in-string
               "\\`\\[.*?]\\*\\|\\[.*?]\\*\\'" "" crm-separator)
              (car args))
      (cdr args)))
   (advice-add #'completing-read-multiple :filter-args #'crm-indicator)

   ;; Do not allow the cursor in the minibuffer prompt
   (setq minibuffer-prompt-properties
         '(read-only t cursor-intangible t face minibuffer-prompt))
   (add-hook 'minibuffer-setup-hook #'cursor-intangible-mode))
#+END_SRC

*** vertico-directory

#+begin_src emacs-lisp
  ;; Configure directory extension.
  (use-package
   vertico-directory
   :after vertico
   :ensure nil
   ;; More convenient directory navigation commands
   :bind
   (:map
    vertico-map
    ("RET" . vertico-directory-enter)
    ("DEL" . vertico-directory-delete-char)
    ("M-DEL" . vertico-directory-delete-word))
   ;; Tidy shadowed file names
   :hook (rfn-eshadow-update-overlay . vertico-directory-tidy))
#+end_src

** orderless 无序搜索

#+begin_src emacs-lisp
  ;; orderless 是一种哲学思想
  (use-package
   orderless
   :custom
   ;; Configure a custom style dispatcher (see the Consult wiki)
   (orderless-style-dispatchers
    '(+orderless-consult-dispatch orderless-affix-dispatch))
   (orderless-component-separator #'orderless-escapable-split-on-space)
   (completion-styles '(orderless-flex flex))
   (completion-category-defaults nil)
   (completion-category-overrides '((file (styles partial-completion)))))
#+end_src

** ~marginalia~ 增加提示信息支持

#+BEGIN_SRC emacs-lisp
  (use-package
   marginalia
   :after vertico
   :config (marginalia-mode)
   :custom
   (marginalia-annotators
    '(marginalia-annotators-heavy marginalia-annotators-light nil)))
#+END_SRC

** consult 配置

~consult~ 提供查询

#+BEGIN_SRC emacs-lisp
  (use-package
   consult
   :ensure t
   :after org
   :bind
   ( ;; C-c bindings in `mode-specific-map'
    ("C-c M-x" . consult-mode-command)
    ("C-c h" . consult-history)
    ("C-c k" . consult-kmacro)
    ("C-c m" . consult-man)
    ("C-c i" . consult-info)
    ([remap Info-search] . consult-info)
    ;; C-x bindings in `ctl-x-map'
    ("C-x M-:" . consult-complex-command) ;; orig. repeat-complex-command
    ("C-x b" . consult-buffer) ;; orig. switch-to-buffer
    ("C-x 4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
    ("C-x 5 b" . consult-buffer-other-frame) ;; orig. switch-to-buffer-other-frame
    ("C-x t b" . consult-buffer-other-tab) ;; orig. switch-to-buffer-other-tab
    ("C-x r b" . consult-bookmark) ;; orig. bookmark-jump
    ("C-x p b" . consult-project-buffer) ;; orig. project-switch-to-buffer
    ;; Custom M-# bindings for fast register access
    ("M-#" . consult-register-load)
    ("M-'" . consult-register-store) ;; orig. abbrev-prefix-mark (unrelated)
    ("C-M-#" . consult-register)
    ;; Other custom bindings
    ("M-y" . consult-yank-pop) ;; orig. yank-pop
    ;; M-g bindings in `goto-map'
    ("M-g e" . consult-compile-error)
    ("M-g f" . consult-flymake) ;; Alternative: consult-flycheck
    ("M-g g" . consult-goto-line) ;; orig. goto-line
    ("M-g M-g" . consult-goto-line) ;; orig. goto-line
    ("M-g o" . consult-outline) ;; Alternative: consult-org-heading
    ("M-g m" . consult-mark)
    ("M-g k" . consult-global-mark)
    ("M-g i" . consult-imenu)
    ("M-g I" . consult-imenu-multi)
    ;; M-s bindings in `search-map'
    ("M-s d" . consult-find) ;; Alternative: consult-fd
    ("M-s c" . consult-locate)
    ("M-s g" . consult-grep)
    ("M-s G" . consult-git-grep)
    ("M-s r" . consult-ripgrep)
    ("M-s l" . consult-line)
    ("M-s L" . consult-line-multi)
    ("M-s k" . consult-keep-lines)
    ("M-s u" . consult-focus-lines)
    ;; Isearch integration
    ("M-s e" . consult-isearch-history)
    :map
    isearch-mode-map
    ("M-e" . consult-isearch-history) ;; orig. isearch-edit-string
    ("M-s e" . consult-isearch-history) ;; orig. isearch-edit-string
    ("M-s l" . consult-line) ;; needed by consult-line to detect isearch
    ("M-s L" . consult-line-multi) ;; needed by consult-line to detect isearch
    ;; Minibuffer history
    :map
    minibuffer-local-map
    ("M-s" . consult-history) ;; orig. next-matching-history-element
    ("M-r" . consult-history) ;; orig. previous-matching-history-element
    :map
    org-mode-map
    ("C-c C-j" . consult-outline))
   :hook (completion-list-mode . consult-preview-at-point-mode)
   :init
   (setq
    register-preview-delay 0.5
    register-preview-function #'consult-register-format)
   (advice-add #'register-preview :override #'consult-register-window)
   (setq
    xref-show-xrefs-function #'consult-xref
    xref-show-definitions-function #'consult-xref))
#+END_SRC

** corfu 补全框架

[[https://github.com/minad/corfu][corfu 是一个补全框架，相较于 ~company~ 更加现代化]]

#+BEGIN_SRC emacs-lisp
  (use-package
   corfu
   :init (global-corfu-mode)
   ;:custom
   ;(corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
   ;(corfu-auto t)                 ;; Enable auto completion
   ;(corfu-separator ?\s)          ;; Orderless field separator
   ;(corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
   ;(corfu-quit-no-match nil)      ;; Never quit, even if there is no match
   ;(corfu-preview-current nil)    ;; Disable current candidate preview
   ;(corfu-preselect 'prompt)      ;; Preselect the prompt
   ;(corfu-on-exact-match nil)     ;; Configure handling of exact matches
   ;(corfu-scroll-margin 5)        ;; Use scroll margin
   )
#+END_SRC

** cape 补全框架

#+BEGIN_SRC emacs-lisp
  (use-package
   cape
   ;; Bind prefix keymap providing all Cape commands under a mnemonic key.
   ;; Press C-c p ? to for help.
   ;:bind ("C-c p" . cape-prefix-map) ;; Alternative keys: M-p, M-+, ...
   ;; Alternatively bind Cape commands individually.
   ;; :bind (("C-c p d" . cape-dabbrev)
   ;;        ("C-c p h" . cape-history)
   ;;        ("C-c p f" . cape-file)
   ;;        ...)
   :init
   ;; Add to the global default value of `completion-at-point-functions' which is
   ;; used by `completion-at-point'.  The order of the functions matters, the
   ;; first function returning a result wins.  Note that the list of buffer-local
   ;; completion functions takes precedence over the global list.
   (add-to-list 'completion-at-point-functions #'cape-file)
   (add-to-list 'completion-at-point-functions #'cape-dabbrev)
   (add-to-list 'completion-at-point-functions #'cape-keyword) ; programming language keyword
   (add-to-list 'completion-at-point-functions #'cape-dict)
   (add-to-list 'completion-at-point-functions #'cape-elisp-symbol) ; elisp symbol
   (add-to-list 'completion-at-point-functions #'cape-elisp-block)
   (add-to-list 'completion-at-point-functions #'cape-line)
   (add-hook 'completion-at-point-functions #'cape-history)
   :config (advice-add 'pcomplete-completions-at-point :around #'cape-wrap-purify)
   ;; ...
   )
#+END_SRC

** yasnippet 补全框架

补全框架 yasnippet

考虑做些修改

#+BEGIN_SRC emacs-lisp
  (use-package
   yasnippet
   :hook
   (prog-mode . yas-minor-mode)
   (org-mode . yas-minor-mode)
   :config (yas-reload-all))

  (use-package
   doom-snippets
   :ensure
   (doom-snippets
    :type git
    :host github
    :repo "doomemacs/snippets"
    :files ("*.el" "*"))
   :after yasnippet)

  ;; 再装一个通用模板库，省得没 template 用
  (use-package yasnippet-snippets :after (yasnippet))
#+END_SRC

** init-completion.el 文件尾

#+BEGIN_SRC emacs-lisp

(provide 'init-completion)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init-completion.el ends here
#+END_SRC

* init-dev.tl
:PROPERTIES:
:HEADER-ARGS: :tangle lisp/init-dev.el :mkdirp yes
:END:

开发使用的一些工具！

** init-dev.el 文件头
#+BEGIN_SRC emacs-lisp
;;; init-dev.el --- Development settings -*- lexical-binding: t -*-
;;; Commentary:

;;; Code:

#+END_SRC

** magit 版本管理

[[https://github.com/magit/magit][magit]] 是Emacs里的另一个杀手级应用！可以直接在Emacs里进行基于git的版本管理。

#+begin_src emacs-lisp
  (use-package magit)
#+end_src

** diff-hl高亮显示修改的部分

[[https://github.com/dgutov/diff-hl][diff-hl]] 插件可以在左侧高亮显示相对于远程仓库的修改部分。

#+BEGIN_SRC emacs-lisp
  (use-package diff-hl :init (global-diff-hl-mode t))
#+END_SRC

** magit-delta增强git diff

[[https://github.com/dandavison/magit-delta][magit-delta]] 插件可以通过 =git-delta= 来更优化的方式显示diff内容（需要提前安装 =git-delta= ）。

#+BEGIN_SRC emacs-lisp
  (use-package magit-delta :hook (magit-mode . magit-delta-mode))
#+END_SRC
** init-dev.el 文件尾
#+BEGIN_SRC emacs-lisp

(provide 'init-dev)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init-dev.el ends here
#+END_SRC

* init-tools.el
:PROPERTIES:
:HEADER-ARGS: :tangle lisp/init-tools.el :mkdirp yes
:END:

** init-tools.el 文件头

#+BEGIN_SRC emacs-lisp
;;; init-tools.el --- Tools settings -*- lexical-binding: t -*-
;;; Commentary: Useful tools to make Emacs efficient!

;;; Code:

#+END_SRC

** helpful帮助增强

[[https://github.com/Wilfred/helpful][helpful]] 插件提供了帮助增强。

#+begin_src emacs-lisp
  (use-package helpful
    :ensure t
    :commands (helpful-callable helpful-variable helpful-command helpful-key helpful-mode)
    :bind (([remap describe-command] . helpful-command)
           ("C-h f" . helpful-callable)
           ("C-h F" . helpful-function)
           ("C-h v" . helpful-variable)
           ("C-c C-d" . heloful-at-point)
           ("C-h x" . helpful-command)
           ([remap describe-key] . helpful-key))
    )
#+end_src

** plz

一个 HTTP 库

#+begin_src emacs-lisp
  (use-package plz)
#+end_src

** go-translate

需要额外配置，目前并不生效！！！

高扩展，配置丰富的翻译框架

#+begin_src emacs-lisp
  (use-package go-translate
    :custom (setq gt-langs '(en zh))
    (setq gt-default-translator (gt-translator :engines (gt-youdao-dict-engine)))
  )
#+end_src

** ch-en-space

一段代码，创建一个 ~mode~ ，允许英文和中文之间自动插入空格，仅在输入时生效
不会破坏文档结构

#+begin_src emacs-lisp
  (defun add-space-between-chinese-and-english ()
    "在中英文之间自动添加空格。"
    (let ((current-char (char-before))
          (prev-char (char-before (1- (point)))))
      (when (and current-char
                 prev-char
                 (or (and (is-chinese-character prev-char)
                          (is-halfwidth-character current-char))
                     (and (is-halfwidth-character prev-char)
                          (is-chinese-character current-char)))
                 (not (eq prev-char ?\s))) ; 检查前一个字符不是空格
        (save-excursion
          (goto-char (1- (point)))
          (insert " ")))))

  (defun is-chinese-character (char)
    "判断字符是否为中文字符。"
    (and char
         (or (and (>= char #x4e00) (<= char #x9fff))
             (and (>= char #x3400) (<= char #x4dbf))
             (and (>= char #x20000) (<= char #x2a6df))
             (and (>= char #x2a700) (<= char #x2b73f))
             (and (>= char #x2b740) (<= char #x2b81f))
             (and (>= char #x2b820) (<= char #x2ceaf)))))

  (defun is-halfwidth-character (char)
    "判断字符是否为半角字符，包括英文字母、数字和标点符号。"
    (and char
         (or (and (>= char ?a) (<= char ?z))
             (and (>= char ?A) (<= char ?Z))
             (and (>= char ?0) (<= char ?9)))))

  (defun delayed-add-space-between-chinese-and-english ()
    "延迟执行，在中英文之间自动添加空格。"
    (run-with-idle-timer 0 nil 'add-space-between-chinese-and-english))

  (define-minor-mode auto-space-mode
    "在中英文之间自动添加空格的模式。"
    :lighter " Auto-Space"
    :global
    t
    (if auto-space-mode
        (add-hook 'post-self-insert-hook 'add-space-between-chinese-and-english)
      (remove-hook
       'post-self-insert-hook 'add-space-between-chinese-and-english)))

  (use-package emacs :ensure nil :hook (org-mode . auto-space-mode))
#+end_src

** init-tools.el 文件尾

#+BEGIN_SRC emacs-lisp

(provide 'init-tools)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init-tools.el ends here
#+END_SRC

* init-lsp.el
:PROPERTIES:
:HEADER-ARGS: :tangle lisp/init-lsp.el :mkdirp yes
:END:

lsp 配置，目前主流的 ~lsp client~ 也就是 ~lsp-mode~ ~eglot~ ~lsp-bridge~ 。

- 其中 ~eglot~ 属于 emacs 内置，无需额外安装，但是确定很明显，它功能不够，并且因为纯 ~elisp~ 实现，速度不快
- 而 ~lsp-mode~ 也是纯 ~elisp~ 实现，不过更完善，包含自动安装 ~lsp server~ 的功能，但更慢，并且由于功能过于复杂，一部分功能可能缺乏维护！
- ~lsp-bridge~ 则是通过 ~python~ 来提高速度，并且支持绝大多数的 ~server~ ，并且是国人制作！

** init-lsp.el 文件头
#+BEGIN_SRC emacs-lisp
;;; init-lsp.el --- Development settings -*- lexical-binding: t -*-
;;; Commentary:

;;; Code:

#+END_SRC

** lsp-bridge 配置

[[https://github.com/manateelazycat/lsp-bridge][lsp-bridge]] 是一个由 ~python~ 实现的 lsp client。

#+begin_quote
lsp-bridge 的目标是使用多线程技术实现 Emacs 生态中速度最快的 LSP 客户端， 开箱即用的设计理念， 节省你自己折腾的时间， 时间就是金钱。
#+end_quote

lsp-bridge 的优势：

1. 速度超快： 把 LSP 的请求等待和数据分析都隔离到外部进程， 不会因为 LSP Server 返回延迟或大量数据触发 GC 而卡住 Emacs
2. 远程补全： 内置远程服务器代码补全， 支持密码、 公钥等多种登录方式， 支持 tramp 协议， 支持 SSH 多级堡垒机跳转, 支持 Docker
3. 开箱即用： 安装后立即可以使用， 不需要额外的配置， 不需要自己折腾补全前端、 补全后端以及多后端融合等配置
4. 多服务器融合： 只需要一个简单的 JSON 即可混合多个 LSP Server 为同一个文件提供服务， 例如 Python， Pyright 提供代码补全， Ruff 提供诊断和格式化
5. 灵活的自定义： 自定义 LSP Server 选项只需要一个 JSON 文件即可， 简单的几行规则就可以让不同的项目使用不同 JSON 配置

需要 ~python~ 依赖：

- ~epc~
- ~orjson~
- ~sexpdata~
- ~six~
- ~setuptools~
- ~setuptools~
- ~rapidfuzz~
   
#+begin_src emacs-lisp
  (use-package
   lsp-bridge
   :ensure
   '(lsp-bridge
     :type git
     :host github
     :repo "manateelazycat/lsp-bridge"
     :files
     (:defaults "*.el" "*.py" "acm" "core" "langserver" "multiserver" "resources")
     :build (:not compile))
   :init (global-lsp-bridge-mode))
#+end_src

** init-lsp.el 文件尾

#+BEGIN_SRC emacs-lisp

(provide 'init-lsp)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init-lsp.el ends here
#+END_SRC

* init-treesitter.el
:PROPERTIES:
:HEADER-ARGS: :tangle lisp/init-treesitter.el :mkdirp yes
:END:

** init-treesitter.el 文件头

#+BEGIN_SRC emacs-lisp
;;; init-treesitter.el --- Tools settings -*- lexical-binding: t -*-
;;; Commentary: Useful tools to make Emacs efficient!

;;; Code:

#+END_SRC

** treesit-auto

~treesit-auto~ 是一个自动安装 treesitter 的插件，但是需要对应的 lang 有相应的 ~ts-mode~ 。

#+begin_src emacs-lisp
  (use-package
   treesit-auto
   :custom (treesit-auto-install 'prompt)
   :config
   (treesit-auto-add-to-auto-mode-alist 'all)
   (global-treesit-auto-mode)
   (treesit-auto-add-to-auto-mode-alist))
#+end_src

** ts-fold

利用 treesitter 进行代码折叠。

#+begin_src emacs-lisp
  (use-package ts-fold
    :ensure (ts-fold :type git :host github :repo "emacs-tree-sitter/ts-fold"))
#+end_src

** init-treesitter.el 文件尾

#+BEGIN_SRC emacs-lisp

(provide 'init-treesitter)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init-treesitter.el ends here
#+END_SRC

* init-book.el
:PROPERTIES:
:HEADER-ARGS: :tangle lisp/init-book.el :mkdirp yes
:END:

** init-book.el 文件头

#+BEGIN_SRC emacs-lisp
;;; init-book.el --- Tools settings -*- lexical-binding: t -*-
;;; Commentary: Useful tools to make Emacs efficient!

;;; Code:

#+END_SRC

** nov

[[https://depp.brause.cc/nov.el/][nov]] 让 emacs 支持阅读 equb，相当棒的插件！

#+begin_src emacs-lisp
  (use-package
   nov
   :mode ("\\.epub\\'" . nov-mode)
   :bind
   (:map nov-mode-map ("j" . scroll-up-line) ("k" . scroll-down-line)))
#+end_src

** calibredb.el

emacs 的 calibredb 客户端，支持在 emacs 中管理和阅读图书！

#+begin_src emacs-lisp
  (use-package
   calibredb
   :commands calibredb
   :bind ("\e\e b" . calibredb)
   :config
   (setq calibredb-root-dir "~/Calibre")
   (setq calibredb-db-dir (expand-file-name "metadata.db" calibredb-root-dir))
   (setq calibredb-library-alist '(("~/Books/books"))))
#+end_src

** init-book.el 文件尾

#+BEGIN_SRC emacs-lisp

(provide 'init-book)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init-book.el ends here
#+END_SRC

* init-lang.el
:PROPERTIES:
:HEADER-ARGS: :tangle lisp/init-lang.el :mkdirp yes
:END:

** init-lang.el 文件头

#+BEGIN_SRC emacs-lisp
;;; init-lang.el --- Tools settings -*- lexical-binding: t -*-
;;; Commentary: Useful tools to make Emacs efficient!

;;; Code:

#+END_SRC

** zig-mode for ziglang

~zig-mode~ 是一个由 ziglang 官方维护的包。

#+begin_src emacs-lisp
  (use-package zig-mode)
#+end_src

** elisp format

[[https://codeberg.org/ideasman42/emacs-elisp-autofmt][elisp-autofmt]] ，用于自动格式化 elisp 代码。

#+begin_src emacs-lisp
  (use-package elisp-autofmt
    :commands (elisp-autofmt-mode elisp-autofmt-buffer)
    :hook (emacs-lisp-mode . elisp-autofmt-mode))
#+end_src

** init-lang.el 文件尾

#+BEGIN_SRC emacs-lisp

(provide 'init-lang)
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; init-lang.el ends here
#+END_SRC
